### ISSUE TITLE
Fail GitHub tagging if already exists

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/attest-release-scripts#3]
Based on this discussion from here - https://github.com/dequelabs/attest-node-suite/pull/105#issuecomment-469717490

> At some point, we may have to add some checks in dequelabs/attest-release-scripts:src/node-github-release.sh@develop (raw), to validate if a tag already exists and warn, to avoid us from overriding.

**Comment by stephenmathieson** [comment]
@jeeyyy  is this considered blocking? I'd like to finish the task I was given without having to worry about edge cases like this

**Comment by jeeyyy** [comment]
Have never ran into this issue after. So can look past this as an issue. Closing.
